
export type APICountry = 'AD' |'AE' |'AF' |'AG' |'AI' |'AL' |'AM' |'AO' |'AQ' |'AR' |'AS' |'AT' |'AU' |'AW' |'AX' |'AZ' |'BA' |'BB' |'BD' |'BE' |'BF' |'BG' |'BH' |'BI' |'BJ' |'BL' |'BM' |'BN' |'BO' |'BQ' |'BR' |'BS' |'BT' |'BV' |'BW' |'BY' |'BZ' |'CA' |'CC' |'CD' |'CF' |'CG' |'CH' |'CI' |'CK' |'CL' |'CM' |'CN' |'CO' |'CR' |'CU' |'CV' |'CW' |'CX' |'CY' |'CZ' |'DE' |'DJ' |'DK' |'DM' |'DO' |'DZ' |'EC' |'EE' |'EG' |'EH' |'ER' |'ES' |'ET' |'FI' |'FJ' |'FK' |'FM' |'FO' |'FR' |'GA' |'GB' |'GD' |'GE' |'GF' |'GG' |'GH' |'GI' |'GL' |'GM' |'GN' |'GP' |'GQ' |'GR' |'GS' |'GT' |'GU' |'GW' |'GY' |'HK' |'HM' |'HN' |'HR' |'HT' |'HU' |'ID' |'IE' |'IL' |'IM' |'IN' |'IO' |'IQ' |'IR' |'IS' |'IT' |'JE' |'JM' |'JO' |'JP' |'KE' |'KG' |'KH' |'KI' |'KM' |'KN' |'KP' |'KR' |'KW' |'KY' |'KZ' |'LA' |'LB' |'LC' |'LI' |'LK' |'LR' |'LS' |'LT' |'LU' |'LV' |'LY' |'MA' |'MC' |'MD' |'ME' |'MF' |'MG' |'MH' |'MK' |'ML' |'MM' |'MN' |'MO' |'MP' |'MQ' |'MR' |'MS' |'MT' |'MU' |'MV' |'MW' |'MX' |'MY' |'MZ' |'NA' |'NC' |'NE' |'NF' |'NG' |'NI' |'NL' |'NO' |'NP' |'NR' |'NU' |'NZ' |'OM' |'PA' |'PE' |'PF' |'PG' |'PH' |'PK' |'PL' |'PM' |'PN' |'PR' |'PS' |'PT' |'PW' |'PY' |'QA' |'RE' |'RO' |'RS' |'RU' |'RW' |'SA' |'SB' |'SC' |'SD' |'SE' |'SG' |'SH' |'SI' |'SJ' |'SK' |'SL' |'SM' |'SN' |'SO' |'SR' |'SS' |'ST' |'SV' |'SX' |'SY' |'SZ' |'TC' |'TD' |'TF' |'TG' |'TH' |'TJ' |'TK' |'TL' |'TM' |'TN' |'TO' |'TR' |'TT' |'TV' |'TW' |'TZ' |'UA' |'UG' |'UM' |'US' |'UY' |'UZ' |'VA' |'VC' |'VE' |'VG' |'VI' |'VN' |'VU' |'WF' |'WS' |'YE' |'YT' |'ZA' |'ZM' |'ZW' ;

export const APICountries = {
	AD:{ en: "Andorra", code:'AD', dial: "+376" },
	AE:{ en: "United Arab Emirates (the)", code:'AE', dial: "+971" },
	AF:{ en: "Afghanistan", code:'AF', dial: "+93" },
	AG:{ en: "Antigua and Barbuda", code:'AG', dial: "+1268" },
	AI:{ en: "Anguilla", code:'AI', dial: "+1264" },
	AL:{ en: "Albania", code:'AL', dial: "+355" },
	AM:{ en: "Armenia", code:'AM', dial: "+374" },
	AN:{ en: "Netherlands Antilles", code: "AN", dial: "+599" },
	AO:{ en: "Angola", code:'AO', dial: "+244" },
	AQ:{ en: "Antarctica", code:'AQ', dial: "+672" },
	AR:{ en: "Argentina", code:'AR', dial: "+54" },
	AS:{ en: "American Samoa", code:'AS', dial: "+1684" },
	AT:{ en: "Austria", code:'AT', dial: "+43" },
	AU:{ en: "Australia", code:'AU', dial: "+61" },
	AW:{ en: "Aruba", code:'AW', dial: "+297" },
	AX:{ en: "Åland Islands", code:'AX', dial: "+358" },
	AZ:{ en: "Azerbaijan", code:'AZ', dial: "+994" },
	BA:{ en: "Bosnia and Herzegovina", code:'BA', dial: "+387" },
	BB:{ en: "Barbados", code:'BB', dial: "+1246"  },
	BD:{ en: "Bangladesh", code:'BD', dial: "+880" },
	BE:{ en: "Belgium", code:'BE', dial: "+32" },
	BF:{ en: "Burkina Faso", code:'BF', dial: "+226" },
	BG:{ en: "Bulgaria", code:'BG', dial: "+359" },
	BH:{ en: "Bahrain", code:'BH', dial: "+973" },
	BI:{ en: "Burundi", code:'BI', dial: "+257" },
	BJ:{ en: "Benin", code:'BJ', dial: "+229" },
	BL:{ en: "Saint Barthélemy", code:'BL', dial: "+590" },
	BM:{ en: "Bermuda", code:'BM', dial: "+1441"  },
	BN:{ en: "Brunei Darussalam", code:'BN', dial: "+673" },
	BO:{ en: "Bolivia (Plurinational State of)", code:'BO', dial: "+591" },
	BQ:{ en: "Bonaire, Sint Eustatius and Saba", code:'BQ', dial:"" },
	BR:{ en: "Brazil", code:'BR', dial: "+55" },
	BS:{ en: "Bahamas (the)", code:'BS', dial: "+1242"  },
	BT:{ en: "Bhutan", code:'BT', dial: "+975" },
	BV:{ en: "Bouvet Island", code:'BV', dial:"" },
	BW:{ en: "Botswana", code:'BW', dial: "+267" },
	BY:{ en: "Belarus", code:'BY', dial: "+375" },
	BZ:{ en: "Belize", code:'BZ', dial: "+501" },
	CA:{ en: "Canada", code:'CA', dial: "+1" },
	CC:{ en: "Cocos (Keeling) Islands (the)", code:'CC', dial: "+61" },
	CD:{ en: "Congo (the Democratic Republic of the)", code:'CD', dial: "+243" },
	CF:{ en: "Central African Republic (the)", code:'CF', dial: "+236" },
	CG:{ en: "Congo (the)", code:'CG', dial: "+242" },
	CH:{ en: "Switzerland", code:'CH', dial: "+41" },
	CI:{ en: "Côte d'Ivoire", code:'CI', dial: "+225" },
	CK:{ en: "Cook Islands (the)", code:'CK', dial: "+682" },
	CL:{ en: "Chile", code:'CL', dial: "+56" },
	CM:{ en: "Cameroon", code:'CM', dial: "+237" },
	CN:{ en: "China", code:'CN', dial: "+86" },
	CO:{ en: "Colombia", code:'CO', dial: "+57" },
	CR:{ en: "Costa Rica", code:'CR', dial: "+506" },
	CU:{ en: "Cuba", code:'CU', dial: "+53" },
	CV:{ en: "Cabo Verde", code:'CV', dial: "+238" },
	CW:{ en: "Curaçao", code:'CW', dial:"" },
	CX:{ en: "Christmas Island", code:'CX', dial: "+61" },
	CY:{ en: "Cyprus", code:'CY', dial: "+357" },
	CZ:{ en: "Czechia", code:'CZ', dial: "+420" },
	DE:{ en: "Germany", code:'DE', dial: "+49" },
	DJ:{ en: "Djibouti", code:'DJ', dial: "+253" },
	DK:{ en: "Denmark", code:'DK', dial: "+45" },
	DM:{ en: "Dominica", code:'DM', dial: "+1767"  },
	DO:{ en: "Dominican Republic (the)", code:'DO', dial: "+1849" },
	DZ:{ en: "Algeria", code:'DZ', dial: "+213" },
	EC:{ en: "Ecuador", code:'EC', dial: "+593" },
	EE:{ en: "Estonia", code:'EE', dial: "+372" },
	EG:{ en: "Egypt", code:'EG', dial: "+20" },
	EH:{ en: "Western Sahara", code:'EH', dial:"" },
	ER:{ en: "Eritrea", code:'ER', dial: "+291" },
	ES:{ en: "Spain", code:'ES', dial: "+34" },
	ET:{ en: "Ethiopia", code:'ET', dial: "+251" },
	FI:{ en: "Finland", code:'FI', dial: "+358" },
	FJ:{ en: "Fiji", code:'FJ', dial: "+679" },
	FK:{ en: "Falkland Islands (the) [Malvinas]", code:'FK', dial: "+500" },
	FM:{ en: "Micronesia (Federated States of)", code:'FM', dial: "+691" },
	FO:{ en: "Faroe Islands (the)", code:'FO', dial: "+298" },
	FR:{ en: "France", code:'FR', dial: "+33" },
	GA:{ en: "Gabon", code:'GA', dial: "+241" },
	GB:{ en: "United Kingdom of Great Britain and Northern Ireland (the)", code:'GB', dial: "+44" },
	GD:{ en: "Grenada", code:'GD', dial: "+1473" },
	GE:{ en: "Georgia", code:'GE', dial: "+995" },
	GF:{ en: "French Guiana", code:'GF', dial: "+594" },
	GG:{ en: "Guernsey", code:'GG', dial: "+44" },
	GH:{ en: "Ghana", code:'GH', dial: "+233" },
	GI:{ en: "Gibraltar", code:'GI', dial: "+350" },
	GL:{ en: "Greenland", code:'GL', dial: "+299" },
	GM:{ en: "Gambia (the)", code:'GM', dial: "+220" },
	GN:{ en: "Guinea", code:'GN', dial: "+224" },
	GP:{ en: "Guadeloupe", code:'GP', dial: "+590" },
	GQ:{ en: "Equatorial Guinea", code:'GQ', dial: "+240" },
	GR:{ en: "Greece", code:'GR', dial: "+30" },
	GS:{ en: "South Georgia and the South Sandwich Islands", code:'GS', dial: "+500" },
	GT:{ en: "Guatemala", code:'GT', dial: "+502" },
	GU:{ en: "Guam", code:'GU', dial: "+1671"  },
	GW:{ en: "Guinea-Bissau", code:'GW', dial: "+245" },
	GY:{ en: "Guyana", code:'GY', dial: "+595" },
	HK:{ en: "Hong Kong", code:'HK', dial: "+852" },
	HM:{ en: "Heard Island and McDonald Islands", code:'HM', dial:"" },
	HN:{ en: "Honduras", code:'HN', dial: "+504" },
	HR:{ en: "Croatia", code:'HR', dial: "+385" },
	HT:{ en: "Haiti", code:'HT', dial: "+509" },
	HU:{ en: "Hungary", code:'HU', dial: "+36" },
	ID:{ en: "Indonesia", code:'ID', dial: "+62" },
	IE:{ en: "Ireland", code:'IE', dial: "+353" },
	IL:{ en: "Israel", code:'IL', dial: "+972" },
	IM:{ en: "Isle of Man", code:'IM', dial: "+44" },
	IN:{ en: "India", code:'IN', dial: "+91" },
	IO:{ en: "British Indian Ocean Territory (the)", code:'IO', dial: "+246" },
	IQ:{ en: "Iraq", code:'IQ', dial: "+964" },
	IR:{ en: "Iran (Islamic Republic of)", code:'IR', dial: "+98" },
	IS:{ en: "Iceland", code:'IS', dial: "+354" },
	IT:{ en: "Italy", code:'IT', dial: "+39" },
	JE:{ en: "Jersey", code:'JE', dial: "+44" },
	JM:{ en: "Jamaica", code:'JM', dial: "+1876" },
	JO:{ en: "Jordan", code:'JO', dial: "+962" },
	JP:{ en: "Japan", code:'JP', dial: "+81" },
	KE:{ en: "Kenya", code:'KE', dial: "+254" },
	KG:{ en: "Kyrgyzstan", code:'KG', dial: "+996" },
	KH:{ en: "Cambodia", code:'KH', dial: "+686" },
	KI:{ en: "Kiribati", code:'KI', dial: "+855" },
	KM:{ en: "Comoros (the)", code:'KM', dial: "+269" },
	KN:{ en: "Saint Kitts and Nevis", code:'KN', dial: "+1869"  },
	KP:{ en: "Korea (the Democratic People's Republic of)", code:'KP', dial: "+850" },
	KR:{ en: "Korea (the Republic of)", code:'KR', dial: "+82" },
	KW:{ en: "Kuwait", code:'KW', dial: "+965" },
	KY:{ en: "Cayman Islands (the)", code:'KY', dial: "+ 345" },
	KZ:{ en: "Kazakhstan", code:'KZ', dial: "+77"  },
	LA:{ en: "Lao People's Democratic Republic (the)", code:'LA', dial: "+856" },
	LB:{ en: "Lebanon", code:'LB', dial: "+961" },
	LC:{ en: "Saint Lucia", code:'LC', dial: "+1758"  },
	LI:{ en: "Liechtenstein", code:'LI', dial: "+423" },
	LK:{ en: "Sri Lanka", code:'LK', dial: "+94" },
	LR:{ en: "Liberia", code:'LR', dial: "+231" },
	LS:{ en: "Lesotho", code:'LS', dial: "+266" },
	LT:{ en: "Lithuania", code:'LT', dial: "+370" },
	LU:{ en: "Luxembourg", code:'LU', dial: "+352" },
	LV:{ en: "Latvia", code:'LV', dial: "+371" },
	LY:{ en: "Libya", code:'LY', dial: "+218" },
	MA:{ en: "Morocco", code:'MA', dial: "+212" },
	MC:{ en: "Monaco", code:'MC', dial: "+377" },
	MD:{ en: "Moldova (the Republic of)", code:'MD', dial: "+373" },
	ME:{ en: "Montenegro", code:'ME', dial: "+382" },
	MF:{ en: "Saint Martin (French part)", code:'MF', dial: "+590" },
	MG:{ en: "Madagascar", code:'MG', dial: "+261" },
	MH:{ en: "Marshall Islands (the)", code:'MH', dial: "+692" },
	MK:{ en: "Republic of North Macedonia", code:'MK', dial: "+389" },
	ML:{ en: "Mali", code:'ML', dial: "+223" },
	MM:{ en: "Myanmar", code:'MM', dial: "+95" },
	MN:{ en: "Mongolia", code:'MN', dial: "+976" },
	MO:{ en: "Macao", code:'MO', dial: "+853" },
	MP:{ en: "Northern Mariana Islands (the)", code:'MP', dial: "+1670"  },
	MQ:{ en: "Martinique", code:'MQ', dial: "+596" },
	MR:{ en: "Mauritania", code:'MR', dial: "+222" },
	MS:{ en: "Montserrat", code:'MS', dial: "+1664" },
	MT:{ en: "Malta", code:'MT', dial: "+356" },
	MU:{ en: "Mauritius", code:'MU', dial: "+230" },
	MV:{ en: "Maldives", code:'MV', dial: "+960" },
	MW:{ en: "Malawi", code:'MW', dial: "+265" },
	MX:{ en: "Mexico", code:'MX', dial: "+52" },
	MY:{ en: "Malaysia", code:'MY', dial: "+60" },
	MZ:{ en: "Mozambique", code:'MZ', dial: "+258" },
	NA:{ en: "Namibia", code:'NA', dial: "+264" },
	NC:{ en: "New Caledonia", code:'NC', dial: "+687" },
	NE:{ en: "Niger (the)", code:'NE', dial: "+227" },
	NF:{ en: "Norfolk Island", code:'NF', dial: "+672" },
	NG:{ en: "Nigeria", code:'NG', dial: "+234" },
	NI:{ en: "Nicaragua", code:'NI', dial: "+505" },
	NL:{ en: "Netherlands (the)", code:'NL', dial: "+31" },
	NO:{ en: "Norway", code:'NO', dial: "+47" },
	NP:{ en: "Nepal", code:'NP', dial: "+977" },
	NR:{ en: "Nauru", code:'NR', dial: "+674" },
	NU:{ en: "Niue", code:'NU', dial: "+683" },
	NZ:{ en: "New Zealand", code:'NZ', dial: "+64" },
	OM:{ en: "Oman", code:'OM', dial: "+968" },
	PA:{ en: "Panama", code:'PA', dial: "+507" },
	PE:{ en: "Peru", code:'PE', dial: "+51" },
	PF:{ en: "French Polynesia", code:'PF', dial: "+689" },
	PG:{ en: "Papua New Guinea", code:'PG', dial: "+675" },
	PH:{ en: "Philippines (the)", code:'PH', dial: "+63" },
	PK:{ en: "Pakistan", code:'PK', dial: "+92" },
	PL:{ en: "Poland", code:'PL', dial: "+48" },
	PM:{ en: "Saint Pierre and Miquelon", code:'PM', dial: "+508" },
	PN:{ en: "Pitcairn", code:'PN', dial: "+872" },
	PR:{ en: "Puerto Rico", code:'PR', dial: "+1939" },
	PS:{ en: "Palestine, State of", code:'PS', dial: "+970" },
	PT:{ en: "Portugal", code:'PT', dial: "+351" },
	PW:{ en: "Palau", code:'PW', dial: "+680" },
	PY:{ en: "Paraguay", code:'PY', dial: "+595" },
	QA:{ en: "Qatar", code:'QA', dial: "+974" },
	RE:{ en: "Réunion", code:'RE', dial: "+262" },
	RO:{ en: "Romania", code:'RO', dial: "+40" },
	RS:{ en: "Serbia", code:'RS', dial: "+381" },
	RU:{ en: "Russian Federation (the)", code:'RU', dial: "+7" },
	RW:{ en: "Rwanda", code:'RW', dial: "+250" },
	SA:{ en: "Saudi Arabia", code:'SA', dial: "+966" },
	SB:{ en: "Solomon Islands", code:'SB', dial: "+677" },
	SC:{ en: "Seychelles", code:'SC', dial: "+248" },
	SD:{ en: "Sudan (the)", code:'SD', dial: "+249" },
	SE:{ en: "Sweden", code:'SE', dial: "+46" },
	SG:{ en: "Singapore", code:'SG', dial: "+65" },
	SH:{ en: "Saint Helena, Ascension and Tristan da Cunha", code:'SH', dial: "+290" },
	SI:{ en: "Slovenia", code:'SI', dial: "+386" },
	SJ:{ en: "Svalbard and Jan Mayen", code:'SJ', dial: "+47" },
	SK:{ en: "Slovakia", code:'SK', dial: "+421" },
	SL:{ en: "Sierra Leone", code:'SL', dial: "+232" },
	SM:{ en: "San Marino", code:'SM', dial: "+378" },
	SN:{ en: "Senegal", code:'SN', dial: "+221" },
	SO:{ en: "Somalia", code:'SO', dial: "+252" },
	SR:{ en: "Suriname", code:'SR', dial: "+597" },
	SS:{ en: "South Sudan", code:'SS', dial:"" },
	ST:{ en: "Sao Tome and Principe", code:'ST', dial: "+239" },
	SV:{ en: "El Salvador", code:'SV', dial: "+503" },
	SX:{ en: "Sint Maarten (Dutch part)", code:'SX', dial:"" },
	SY:{ en: "Syrian Arab Republic", code:'SY', dial: "+963" },
	SZ:{ en: "Eswatini", code:'SZ', dial: "+268" },
	TC:{ en: "Turks and Caicos Islands (the)", code:'TC', dial: "+1649"  },
	TD:{ en: "Chad", code:'TD', dial: "+235" },
	TF:{ en: "French Southern Territories (the)", code:'TF', dial:"" },
	TG:{ en: "Togo", code:'TG', dial: "+228" },
	TH:{ en: "Thailand", code:'TH', dial: "+66" },
	TJ:{ en: "Tajikistan", code:'TJ', dial: "+992" },
	TK:{ en: "Tokelau", code:'TK', dial: "+690" },
	TL:{ en: "Timor-Leste", code:'TL', dial: "+670" },
	TM:{ en: "Turkmenistan", code:'TM', dial: "+993" },
	TN:{ en: "Tunisia", code:'TN', dial: "+216" },
	TO:{ en: "Tonga", code:'TO', dial: "+676" },
	TR:{ en: "Turkey", code:'TR', dial: "+90" },
	TT:{ en: "Trinidad and Tobago", code:'TT', dial: "+1868"  },
	TV:{ en: "Tuvalu", code:'TV', dial: "+688" },
	TW:{ en: "Taiwan (Province of China)", code:'TW', dial: "+886" },
	TZ:{ en: "Tanzania, United Republic of", code:'TZ', dial: "+255" },
	UA:{ en: "Ukraine", code:'UA', dial: "+380" },
	UG:{ en: "Uganda", code:'UG', dial: "+256" },
	UM:{ en: "United States Minor Outlying Islands (the)", code:'UM', dial:"" },
	US:{ en: "United States of America (the)", code:'US', dial: "+1" },
	UY:{ en: "Uruguay", code:'UY', dial: "+598" },
	UZ:{ en: "Uzbekistan", code:'UZ', dial: "+998" },
	VA:{ en: "Holy See (the)", code:'VA', dial: "+379" },
	VC:{ en: "Saint Vincent and the Grenadines", code:'VC', dial: "+1784"  },
	VE:{ en: "Venezuela (Bolivarian Republic of)", code:'VE', dial: "+58" },
	VG:{ en: "Virgin Islands (British)", code:'VG', dial: "+1284"  },
	VI:{ en: "Virgin Islands (U.S.)", code:'VI', dial: "+1340" },
	VN:{ en: "Viet Nam", code:'VN', dial: "+84" },
	VU:{ en: "Vanuatu", code:'VU', dial: "+678" },
	WF:{ en: "Wallis and Futuna", code:'WF', dial: "+681" },
	WS:{ en: "Samoa", code:'WS', dial: "+685" },
	YE:{ en: "Yemen", code:'YE', dial: "+967" },
	YT:{ en: "Mayotte", code:'YT', dial: "+262" },
	ZA:{ en: "South Africa", code:'ZA', dial: "+27" },
	ZM:{ en: "Zambia", code:'ZM', dial: "+260" },
	ZW:{ en: "Zimbabwe", code:'ZW', dial: "+263" },
} ;